# Generated by Django 4.2.1 on 2023-08-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
