# Generated by Django 4.2.1 on 2023-08-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='num',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
