# Generated by Django 4.2.1 on 2023-08-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_num_post_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='serial_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
