# Generated by Django 3.2.20 on 2023-08-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_id_alter_post_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='serial_number',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
